[owner]
name = "malloc-nbytes"
github = "https://github.com/malloc-nbytes/earl-test-module.git"

[deps]
clap = "https://github.com/malloc-nbytes/earl-module-clap.git"

[config]
prefix = "test-module"
